name: 'Detect Changes'
author: kerrymGeologicai
description: 'Reusable workflow for identifying changed files in a GitHub event'

inputs:
  github_event:
    description: 'The stringified GitHub event object'
    required: true
    type: string
  github_token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}
outputs:
  changed_files:
    description: 'A newline-separated string of files which were changed'

runs:
  using: 'node16'
  main: 'dist/index.js'